---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: "monitoring"
    meta.helm.sh/release-namespace: "monitoring-stack"
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
  name: monitoring-grafana-config
  namespace: monitoring-stack
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [smtp]
    enabled = true
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    admin_user = "admin"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-ebs
  namespace: monitoring-stack
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: "monitoring"
  name: monitoring-grafana
  namespace: monitoring-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/name: grafana
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777 /var/lib/grafana/dashboards']
        volumeMounts:
        - mountPath: /var/lib/grafana/dashboards
          name: pvc-grafana
      containers:
      - name: grafana
        image: grafana/grafana:8.5.3
        volumeMounts:
        - mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
          name: grafana-config
        - mountPath: /var/lib/grafana
          name: pvc-grafana
        resources:
          limits:
            cpu: 2m
            memory: 1000Mi
          requests:
            cpu: 1m
            memory: 500Mi
      - name: grafana-sc-dashboard
        image: quay.io/kiwigrid/k8s-sidecar:1.15.6
        env:
        - name: LABEL
          value: "grafana-dashboard"
        - name: FOLDER
          value: "/var/lib/grafana/dashboards"
        volumeMounts:
        - mountPath: /var/lib/grafana/dashboards
          name: pvc-grafana
      volumes:
      - name: grafana-config
        configMap:
          name: monitoring-grafana-config
      - name: pvc-grafana
        persistentVolumeClaim:
          claimName: grafana-ebs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoring-stack
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: monitoring-stack
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring-stack
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
