apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [smtp]
    enabled = true
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    admin_user = "admin"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: "monitoring"
    meta.helm.sh/release-namespace: "monitoring-stack"
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    # app.kubernetes.io/version: 8.0.3
    # helm.sh/chart: grafana-6.13.6
  name: monitoring-grafana
  namespace: monitoring-stack
